baseurl         = "https://marinavab.netlify.com/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true


[params]
  sitename = "Marina's blog"
  pagetitle = "Marina Vabistsevits"
  faviconfile = "image/favicon.png"
  subtitle    = "Marina Vabistsevits"
  copyright   = "© 2020"

  cover       = "img/ivette-pena-cover.jpg"
  description = "A website built through Hugo and blogdown."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "marina_vab"
  githubName = "mvab"
  linkedinName = "marina-vabistsevits-82590443"
  mediumName = ""

  logo = "marina-logo-large.gif" #main page
  orgName = "Marina Vabistsevits"
  orgWebsite = "https://marinavab.netlify.com"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Marina Vabistsevits"
  authorAvatar = "img/marina-logo.png" # on blog posts
  authorLocation = "Bristol, UK"
  authorWebsite = "https://marinavab.netlify.com"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 9
  
[[menu.resources]]
  name = "About me"
  url = "/about/"
  weight = 1  

[[menu.main]]
  name = "Blog"
  url = "/categories/"
  weight = 8
  
[[menu.main]]
  name = "CV"
  url = "/vitae/"
  weight = 7
  
  
#[[menu.main]]
#  name = "R blogs"
#  url = "/tags/r/"
#  weight = 7

#[[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 6


