baseurl         = "https://marinalearning.netlify.com/"
theme = "hugo-casper-two"
languageCode    = "en-UK"
title = "Marina's blog"
disqusShortname = ""
paginate        = 6   # number of pages 
#SectionPagesMenu = "main"
canonifyurls    = true


[params]

  title = "I like pretty plots"
  subtitle  = "Marina Vabistsevits's blog"
  #sitename = "Marina's blog"
  faviconfile = "image/favicon.png"
  
  copyright   =  "© 2020"

  cover       = "img/ivette-pena-cover.jpg"
  description = "A website built through Hugo and blogdown."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "marina_vab"
  githubName = "mvab"
  linkedinName = "marina-vabistsevits-82590443"


  #logo = "marina-logo-large.gif" #main page
  orgName = "Marina Vabistsevits" # C2020
  #orgWebsite = "https://marinalearning.netlify.com"
  #orgDescription = "Here is a description placeholder for your org"
#
  showSupport = true

  author = "Marina Vabistsevits"
  authorAvatar = "img/marina-logo.png" # on blog posts
  authorLocation = "Bristol, UK"
  authorWebsite = "https://marinalearning.netlify.com"
  authorDescription = "The maintainer of this blog"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
#  post = "/post/:slug/"
 post = "/:year/:month/:day/:slug/"

  
#[[menu.main]]
#  name = "Home"
#  url = "/"
#  weight = 9


 # really weird - with this commented out, still get a page "about me" 
#[[menu.main]]
#  name = "About"
#  url = "/about/"
#  weight = 10  
  
[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 8
  

#  
#[[menu.main]]
#  name = "Tags"
#  url = "/tags/"
#  weight = 6
  
[[menu.main]]
  name = "CV"
  url = "/vitae/"
  weight = 5  
  
  
#[[menu.main]]
#  name = "R blogs"
#  url = "/tags/r/"
#  weight = 7

#[[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 6

[taxonomies]
  tag = "tags"

