baseurl         = "https://marinavab.netlify.com/"
theme = "hugo-casper-two"
languageCode    = "en-UK"
title = "Marina's blog"
disqusShortname = ""
paginate        = 6   # number of pages 
#SectionPagesMenu = "main"
canonifyurls    = true


[params]

  title = "Hello"
  subtitle  = "Marina Vabistsevits's blog"
  #sitename = "Marina's blog"
  faviconfile = "image/favicon.png"
  
  copyright   = "© 2020"

  cover       = "img/ivette-pena-cover.jpg"
  description = "A website built through Hugo and blogdown."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "marina_vab"
  githubName = "mvab"
  linkedinName = "marina-vabistsevits-82590443"
  mediumName = ""

  logo = "marina-logo-large.gif" #main page
  #orgName = "Marina Vabistsevits"
  #orgWebsite = "https://marinavab.netlify.com"
  #orgDescription = "Here is a description placeholder for your org"
#
  showSupport = true

  author = "Marina Vabistsevits"
  authorAvatar = "img/marina-logo.png" # on blog posts
  authorLocation = "Bristol, UK"
  authorWebsite = "https://marinavab.netlify.com"
  authorDescription = "The maintainer of this blog"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
#  post = "/post/:slug/"
 post = "/:year/:month/:day/:slug/"

  
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 9
  
[[menu.resources]]
  name = "About me"
  url = "/about/"
  weight = 1  

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 8
  
[[menu.main]]
  name = "Browse by categories"
  url = "/categories/"
  weight = 7
  
[[menu.main]]
  name = "CV"
  url = "/vitae/"
  weight = 6
  
  
#[[menu.main]]
#  name = "R blogs"
#  url = "/tags/r/"
#  weight = 7

#[[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 6


